/*
 * Created on 7 oct. 2013 ( Time 12:34:12 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package j2ee.association.test.persistence;


import j2ee.association.bean.Command ;
import j2ee.association.mock.CommandMock;
import j2ee.association.persistence.PersistenceServiceProvider;
import j2ee.association.persistence.services.CommandPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Command persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class CommandPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test Command persistence : delete + load ..." );
		
		CommandPersistence service = PersistenceServiceProvider.getService(CommandPersistence.class);
		
		CommandMock mock = new CommandMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(CommandPersistence service, CommandMock mock, int coId ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Command entity = service.load( coId );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( coId ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Userinfo
			// . Article
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( coId );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
