/*
 * Created on 14 oct. 2013 ( Time 18:54:32 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 

package j2ee.association.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Persistent class for entity stored in table "ARTICLE"
 *
 * @author Telosys Tools Generator
 *
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="ARTICLE", schema="APP" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Article.query1", query="SELECT x FROM Article x WHERE  " ),
//  @NamedQuery ( name="Article.query2", query="SELECT x FROM Article x WHERE  " )
// } )
public class Article implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="AR_ID", nullable=false)
    private String     arId         ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="AR_CODE", nullable=false, length=2)
    private String     arCode       ;

    @Column(name="AR_NAME", nullable=false, length=255)
    private String     arName       ;

    @Column(name="AR_PRICE", nullable=false)
    private double     arPrice      ;

    @Column(name="AR_STOCK", nullable=false)
    private int        arStock      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Article()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setArId( String arId )
    {
        this.arId = arId ;
    }
    public String getArId()
    {
        return this.arId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : AR_CODE ( VARCHAR ) 
    public void setArCode( String arCode )
    {
        this.arCode = arCode;
    }
    public String getArCode()
    {
        return this.arCode;
    }

    //--- DATABASE MAPPING : AR_NAME ( VARCHAR ) 
    public void setArName( String arName )
    {
        this.arName = arName;
    }
    public String getArName()
    {
        return this.arName;
    }

    //--- DATABASE MAPPING : AR_PRICE ( DOUBLE ) 
    public void setArPrice( double arPrice )
    {
        this.arPrice = arPrice;
    }
    public double getArPrice()
    {
        return this.arPrice;
    }

    //--- DATABASE MAPPING : AR_STOCK ( INTEGER ) 
    public void setArStock( int arStock )
    {
        this.arStock = arStock;
    }
    public int getArStock()
    {
        return this.arStock;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(arId); 
        sb.append("|"); 
        sb.append(arCode); 
        sb.append( "|" ); 
        sb.append(arName); 
        sb.append( "|" ); 
        sb.append(arPrice); 
        sb.append( "|" ); 
        sb.append(arStock); 
        return sb.toString(); 
    }

}
