/*
 * Created on 19 oct. 2013 ( Time 12:01:28 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 

package j2ee.association.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import java.util.List;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Persistent class for entity stored in table "COUNTRY"
 *
 * @author Telosys Tools Generator
 *
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="COUNTRY", schema="APP" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Country.query1", query="SELECT x FROM Country x WHERE  " ),
//  @NamedQuery ( name="Country.query2", query="SELECT x FROM Country x WHERE  " )
// } )
public class Country implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="CO_ID", nullable=false)
    private int        coId         ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="CO_NAME", nullable=false, length=255)
    private String     coName       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="country", targetEntity=Userinfo.class)
    private List<Userinfo> listOfUserinfo;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Country()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCoId( int coId )
    {
        this.coId = coId ;
    }
    public int getCoId()
    {
        return this.coId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : CO_NAME ( VARCHAR ) 
    public void setCoName( String coName )
    {
        this.coName = coName;
    }
    public String getCoName()
    {
        return this.coName;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    @XmlTransient
    public void setListOfUserinfo( List<Userinfo> listOfUserinfo )
    {
        this.listOfUserinfo = listOfUserinfo;
    }
    public List<Userinfo> getListOfUserinfo()
    {
        return this.listOfUserinfo;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(coId); 
        sb.append("|"); 
        sb.append(coName); 
        return sb.toString(); 
    }

}
