/*
 * Created on 7 oct. 2013 ( Time 12:34:12 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package j2ee.association.persistence.services.fake;

import java.util.List;
import java.util.Map;

import j2ee.association.bean.Command ;
import j2ee.association.persistence.commons.fake.GenericFakeService;
import j2ee.association.persistence.services.CommandPersistence;

/**
 * Fake persistence service implementation ( entity "Command" )
 *
 * @author Telosys Tools Generator
 */
public class CommandPersistenceFAKE extends GenericFakeService<Command> implements CommandPersistence {

	public CommandPersistenceFAKE () {
		super(Command.class);
	}
	
	protected Command buildEntity(int index) {
		Command entity = new Command();
		// Init fields with mock values
		entity.setCoId( nextInteger() ) ;
		return entity ;
	}
	
	
	public boolean delete(Command entity) {
		log("delete ( Command : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( int coId ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(Command entity) {
		log("insert ( Command : " + entity + ")" ) ;
	}

	public Command load( int coId ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Command> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Command> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Command> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Command save(Command entity) {
		log("insert ( Command : " + entity + ")" ) ;
		return entity;
	}

	public List<Command> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

}
