/*
 * Created on 19 oct. 2013 ( Time 12:01:29 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package j2ee.association.persistence.services.fake;

import java.util.List;
import java.util.Map;

import j2ee.association.bean.Country ;
import j2ee.association.persistence.commons.fake.GenericFakeService;
import j2ee.association.persistence.services.CountryPersistence;

/**
 * Fake persistence service implementation ( entity "Country" )
 *
 * @author Telosys Tools Generator
 */
public class CountryPersistenceFAKE extends GenericFakeService<Country> implements CountryPersistence {

	public CountryPersistenceFAKE () {
		super(Country.class);
	}
	
	protected Country buildEntity(int index) {
		Country entity = new Country();
		// Init fields with mock values
		entity.setCoId( nextInteger() ) ;
		entity.setCoName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(Country entity) {
		log("delete ( Country : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( int coId ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(Country entity) {
		log("insert ( Country : " + entity + ")" ) ;
	}

	public Country load( int coId ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Country> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Country> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Country> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Country save(Country entity) {
		log("insert ( Country : " + entity + ")" ) ;
		return entity;
	}

	public List<Country> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

}
