/*
 * Created on 7 oct. 2013 ( Time 10:21:00 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.demo.persistence.services.jpa;

import org.demo.bean.Article ;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.services.ArticlePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Article" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ArticlePersistenceJPA extends GenericJpaService<Article, String> implements ArticlePersistence {

	/**
	 * Constructor
	 */
	public ArticlePersistenceJPA() {
		super(Article.class);
	}

	public Article load( String arId ) {
		return super.load( arId );
	}

	public boolean delete( String arId ) {
		return super.delete( arId );
	}

	public boolean delete(Article entity) {
		if ( entity != null ) {
			return super.delete( entity.getArId() );
		}
		return false ;
	}

}
