/*
 * Created on 7 oct. 2013 ( Time 10:21:01 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.demo.persistence.services.jpa;

import org.demo.bean.Catalogue ;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.services.CataloguePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Catalogue" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class CataloguePersistenceJPA extends GenericJpaService<Catalogue, Integer> implements CataloguePersistence {

	/**
	 * Constructor
	 */
	public CataloguePersistenceJPA() {
		super(Catalogue.class);
	}

	public Catalogue load( int caId ) {
		return super.load( caId );
	}

	public boolean delete( int caId ) {
		return super.delete( caId );
	}

	public boolean delete(Catalogue entity) {
		if ( entity != null ) {
			return super.delete( entity.getCaId() );
		}
		return false ;
	}

}
