/*
 * Created on 7 oct. 2013 ( Time 10:21:01 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.demo.persistence.services.jpa;

import org.demo.bean.Command ;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.services.CommandPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Command" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class CommandPersistenceJPA extends GenericJpaService<Command, Integer> implements CommandPersistence {

	/**
	 * Constructor
	 */
	public CommandPersistenceJPA() {
		super(Command.class);
	}

	public Command load( int coId ) {
		return super.load( coId );
	}

	public boolean delete( int coId ) {
		return super.delete( coId );
	}

	public boolean delete(Command entity) {
		if ( entity != null ) {
			return super.delete( entity.getCoId() );
		}
		return false ;
	}

}
