/*
 * Created on 7 oct. 2013 ( Time 10:21:01 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.demo.persistence.services.jpa;

import org.demo.bean.Userinfo ;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.services.UserinfoPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Userinfo" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class UserinfoPersistenceJPA extends GenericJpaService<Userinfo, Integer> implements UserinfoPersistence {

	/**
	 * Constructor
	 */
	public UserinfoPersistenceJPA() {
		super(Userinfo.class);
	}

	public Userinfo load( int usId ) {
		return super.load( usId );
	}

	public boolean delete( int usId ) {
		return super.delete( usId );
	}

	public boolean delete(Userinfo entity) {
		if ( entity != null ) {
			return super.delete( entity.getUsId() );
		}
		return false ;
	}

}
