/*
 * Created on 7 oct. 2013 ( Time 10:21:01 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.demo.persistence.services;

import java.util.List;
import java.util.Map;

import org.demo.bean.Userinfo ;

/**
 * Basic persistence operations for entity "Userinfo"
 * 
 * This Bean has a basic Primary Key : int
 *
 * @author Telosys Tools Generator
 *
 */
public interface UserinfoPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param userinfo
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Userinfo userinfo) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param usId
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(int usId) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param userinfo
	 */
	public void insert(Userinfo userinfo) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param usId
	 * @return the entity loaded (or null if not found)
	 */
	public Userinfo load(int usId) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<Userinfo> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<Userinfo> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<Userinfo> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param userinfo
	 * @return
	 */
	public Userinfo save(Userinfo userinfo) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<Userinfo> search( Map<String, Object> criteria ) ;
}
