/*
 * Created on 7 oct. 2013 ( Time 12:34:12 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package j2ee.association.persistence.services;

import java.util.List;
import java.util.Map;

import j2ee.association.bean.Command ;

/**
 * Basic persistence operations for entity "Command"
 * 
 * This Bean has a basic Primary Key : int
 *
 * @author Telosys Tools Generator
 *
 */
public interface CommandPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param command
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Command command) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param coId
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(int coId) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param command
	 */
	public void insert(Command command) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param coId
	 * @return the entity loaded (or null if not found)
	 */
	public Command load(int coId) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<Command> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<Command> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<Command> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param command
	 * @return
	 */
	public Command save(Command command) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<Command> search( Map<String, Object> criteria ) ;
}
