
/*
 * Created on 7 oct. 2013 ( Time 12:34:12 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package j2ee.association.mock;

import java.util.LinkedList;
import java.util.List;

import j2ee.association.bean.Catalogue ;
import j2ee.association.mock.tool.MockValues;

public class CatalogueMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Catalogue createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Catalogue createInstance( int caId ) {
		Catalogue entity = new Catalogue();
		// Init Primary Key fields
		entity.setCaId( caId) ;
		// Init Data fields
		entity.setCaCode( mockValues.nextString(2) ) ; // java.lang.String 
		entity.setCaName( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setCaPrice( mockValues.nextDouble() ) ; // double 
		entity.setCaStock( mockValues.nextInteger() ) ; // int 
		// Init Link fields (if any)
		// setListOfArticle( TODO ) ; // List<Article> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Catalogue> createList(int count) {
		List<Catalogue> list = new LinkedList<Catalogue>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
