
/*
 * Created on 7 oct. 2013 ( Time 12:34:12 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package j2ee.association.mock;

import java.util.LinkedList;
import java.util.List;

import j2ee.association.bean.Command ;
import j2ee.association.mock.tool.MockValues;

public class CommandMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Command createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Command createInstance( int coId ) {
		Command entity = new Command();
		// Init Primary Key fields
		entity.setCoId( coId) ;
		// Init Data fields
		// Init Link fields (if any)
		// setUserinfo( TODO ) ; // Userinfo 
		// setArticle( TODO ) ; // Article 
		// setListOfArticle( TODO ) ; // List<Article> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Command> createList(int count) {
		List<Command> list = new LinkedList<Command>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
