
/*
 * Created on 19 oct. 2013 ( Time 12:01:29 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package j2ee.association.mock;

import java.util.LinkedList;
import java.util.List;

import j2ee.association.bean.Country ;
import j2ee.association.mock.tool.MockValues;

public class CountryMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Country createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Country createInstance( int coId ) {
		Country entity = new Country();
		// Init Primary Key fields
		entity.setCoId( coId) ;
		// Init Data fields
		entity.setCoName( mockValues.nextString(255) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfUserinfo( TODO ) ; // List<Userinfo> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Country> createList(int count) {
		List<Country> list = new LinkedList<Country>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
