/*
 * Created on 7 oct. 2013 ( Time 10:20:59 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import java.util.List;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Persistent class for entity stored in table "ARTICLE"
 *
 * @author Telosys Tools Generator
 *
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="ARTICLE", schema="APP" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Article.query1", query="SELECT x FROM Article x WHERE  " ),
//  @NamedQuery ( name="Article.query2", query="SELECT x FROM Article x WHERE  " )
// } )
public class Article implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="AR_ID", nullable=false, length=2)
    private String     arId         ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="AR_QUANTITY", nullable=false)
    private int        arQuantity   ;

	// "arCoId" (column "AR_CO_ID") is not defined by itself because used as FK in a link 
	// "arCaId" (column "AR_CA_ID") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="AR_CO_ID", referencedColumnName="CO_ID", insertable=false, updatable=false)
    private Command    command     ;

    @OneToMany(mappedBy="article", targetEntity=Command.class)
    private List<Command> listOfCommand;

    @ManyToOne
    @JoinColumn(name="AR_CA_ID", referencedColumnName="CA_ID", insertable=false, updatable=false)
    private Catalogue  catalogue   ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Article()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setArId( String arId )
    {
        this.arId = arId ;
    }
    public String getArId()
    {
        return this.arId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : AR_QUANTITY ( INTEGER ) 
    public void setArQuantity( int arQuantity )
    {
        this.arQuantity = arQuantity;
    }
    public int getArQuantity()
    {
        return this.arQuantity;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setCommand( Command command )
    {
        this.command = command;
    }
    public Command getCommand()
    {
        return this.command;
    }

    @XmlTransient
    public void setListOfCommand( List<Command> listOfCommand )
    {
        this.listOfCommand = listOfCommand;
    }
    public List<Command> getListOfCommand()
    {
        return this.listOfCommand;
    }

    public void setCatalogue( Catalogue catalogue )
    {
        this.catalogue = catalogue;
    }
    public Catalogue getCatalogue()
    {
        return this.catalogue;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(arId); 
        sb.append("|"); 
        sb.append(arQuantity); 
        return sb.toString(); 
    }

}
