/*
 * Created on 19 oct. 2013 ( Time 12:01:28 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package j2ee.association.persistence.services.jpa;

import j2ee.association.bean.Article ;
import j2ee.association.persistence.commons.jpa.GenericJpaService;
import j2ee.association.persistence.services.ArticlePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Article" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ArticlePersistenceJPA extends GenericJpaService<Article, String> implements ArticlePersistence {

	/**
	 * Constructor
	 */
	public ArticlePersistenceJPA() {
		super(Article.class);
	}

	public Article load( String arId ) {
		return super.load( arId );
	}

	public boolean delete( String arId ) {
		return super.delete( arId );
	}

	public boolean delete(Article entity) {
		if ( entity != null ) {
			return super.delete( entity.getArId() );
		}
		return false ;
	}

}
