/*
 * Created on 20 oct. 2013 ( Time 17:59:59 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package j2ee.association.persistence.services.jpa;

import j2ee.association.bean.Country ;
import j2ee.association.persistence.commons.jpa.GenericJpaService;
import j2ee.association.persistence.services.CountryPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Country" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class CountryPersistenceJPA extends GenericJpaService<Country, Integer> implements CountryPersistence {

	/**
	 * Constructor
	 */
	public CountryPersistenceJPA() {
		super(Country.class);
	}

	public Country load( int coId ) {
		return super.load( coId );
	}

	public boolean delete( int coId ) {
		return super.delete( coId );
	}

	public boolean delete(Country entity) {
		if ( entity != null ) {
			return super.delete( entity.getCoId() );
		}
		return false ;
	}

}
